/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.controller.ColeccionControlador;
import com.controller.ProductoControlador;
import com.controller.TipoProductoControlador;
import com.model.Coleccion;
import com.model.TipoProducto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("App tecnicas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaColeccion = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaTipProducto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTrimestre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        ListarColeccion = new javax.swing.JButton();
        GuardarColeccion = new javax.swing.JButton();
        GuardarTipProducto = new javax.swing.JButton();
        ListarTipProducto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ColeccionProducto = new javax.swing.JButton();
        TipProductoProducto = new javax.swing.JButton();
        txtColeccion = new javax.swing.JTextField();
        txtTipProducto = new javax.swing.JTextField();
        GuardarProducto = new javax.swing.JButton();
        GuardarProducto1 = new javax.swing.JButton();
        GuardarProducto2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 921, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Bienvenida", jPanel1);

        TablaColeccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Trimestre"
            }
        ));
        jScrollPane1.setViewportView(TablaColeccion);

        TablaTipProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Referencia", "Nombre"
            }
        ));
        jScrollPane2.setViewportView(TablaTipProducto);

        jLabel1.setText("Id");

        jLabel2.setText("Trimestre");

        jLabel3.setText("Referencia");

        jLabel4.setText("Nombre");

        ListarColeccion.setText("Listar");
        ListarColeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarColeccionActionPerformed(evt);
            }
        });

        GuardarColeccion.setText("Guardar");
        GuardarColeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarColeccionActionPerformed(evt);
            }
        });

        GuardarTipProducto.setText("Guardar");
        GuardarTipProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarTipProductoActionPerformed(evt);
            }
        });

        ListarTipProducto.setText("Listar");
        ListarTipProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTipProductoActionPerformed(evt);
            }
        });

        jLabel5.setText("Registrar producto");

        jLabel6.setText("Precio:");

        txtPrecio.setToolTipText("Ingrese precio");
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        jLabel7.setText("Cantidad");

        txtCantidad.setToolTipText("Ingrese precio");
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel8.setText("Tipo de producto");

        jLabel9.setText("Coleccion");

        ColeccionProducto.setText("Coleccion");
        ColeccionProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColeccionProductoActionPerformed(evt);
            }
        });

        TipProductoProducto.setText("Tipo de producto");
        TipProductoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipProductoProductoActionPerformed(evt);
            }
        });

        txtColeccion.setEditable(false);
        txtColeccion.setToolTipText("Ingrese precio");

        txtTipProducto.setEditable(false);
        txtTipProducto.setToolTipText("Ingrese precio");

        GuardarProducto.setText("Guardar");
        GuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarProductoActionPerformed(evt);
            }
        });

        GuardarProducto1.setText("Comprar");
        GuardarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarProducto1ActionPerformed(evt);
            }
        });

        GuardarProducto2.setText("Mirar productos");
        GuardarProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarProducto2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(GuardarColeccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ListarColeccion))
                            .addComponent(txtTrimestre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtId))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(ColeccionProducto)
                            .addComponent(TipProductoProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(GuardarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(GuardarProducto1)
                        .addGap(18, 18, 18)
                        .addComponent(GuardarProducto2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReferencia)
                            .addComponent(txtNombre)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(GuardarTipProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ListarTipProducto))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListarColeccion)
                    .addComponent(GuardarColeccion)
                    .addComponent(ListarTipProducto)
                    .addComponent(GuardarTipProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ColeccionProducto)
                                    .addComponent(txtColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TipProductoProducto)
                                    .addComponent(txtTipProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(GuardarProducto)
                                    .addComponent(GuardarProducto1)
                                    .addComponent(GuardarProducto2)))))))
        );

        jTabbedPane1.addTab("Producto", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ColeccionControlador p = new ColeccionControlador();
    TipoProductoControlador q = new TipoProductoControlador();
    ProductoControlador z = new ProductoControlador();
    private void GuardarColeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarColeccionActionPerformed
        if (p.CrearColeccion(txtTrimestre.getText(), txtId.getText())) {
            txtTrimestre.setText("");
            txtId.setText("");
            JOptionPane.showMessageDialog(null, "Los datos se guardaron");
        } else {
            txtTrimestre.setText("");
            txtId.setText("");
            JOptionPane.showMessageDialog(null, "Verifique, ha ocurrido un error");
        }
    }//GEN-LAST:event_GuardarColeccionActionPerformed

    private void ListarColeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarColeccionActionPerformed
        DefaultTableModel model = (DefaultTableModel) TablaColeccion.getModel();
        for (int i = 0; i < TablaColeccion.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }

        List<Coleccion> coleccion = p.ConsultarColecciones();
        for (Coleccion q : coleccion) {
            model.addRow(new Object[]{q.getId(), q.getTrimestre()});
        }
    }//GEN-LAST:event_ListarColeccionActionPerformed

    private void GuardarTipProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarTipProductoActionPerformed
        if (q.CrearTipoProducto(txtReferencia.getText(), txtNombre.getText())) {
            txtReferencia.setText("");
            txtNombre.setText("");
            JOptionPane.showMessageDialog(null, "Los datos se guardaron");
        } else {
            txtReferencia.setText("");
            txtNombre.setText("");
            JOptionPane.showMessageDialog(null, "Verifique, ha ocurrido un error");
        }
    }//GEN-LAST:event_GuardarTipProductoActionPerformed

    private void ListarTipProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTipProductoActionPerformed
        DefaultTableModel model = (DefaultTableModel) TablaTipProducto.getModel();

        for (int i = 0; i < TablaTipProducto.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }

        List<TipoProducto> tipproducto = q.ConsultarTipoProductos();
        for (TipoProducto q : tipproducto) {
            model.addRow(new Object[]{q.getReferencia(), q.getNombre()});
        }
    }//GEN-LAST:event_ListarTipProductoActionPerformed

    private void ColeccionProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColeccionProductoActionPerformed
        String data;
        data = JOptionPane.showInputDialog("Ingrese la coleccion con la que desea guardar el producto");
        data.trim();
        if (p.ColeccionEsta(data) != null) {
            txtColeccion.setText(p.ColeccionEsta(data));
        } else {
            JOptionPane.showMessageDialog(null, "El producto no está");
        }
    }//GEN-LAST:event_ColeccionProductoActionPerformed

    private void TipProductoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipProductoProductoActionPerformed
        String data;
        data = JOptionPane.showInputDialog("Ingrese la coleccion con la que desea guardar el producto");
        data.trim();
        if (q.ProductoEsta(data) != null) {
            txtTipProducto.setText(q.ProductoEsta(data));
        } else {
            JOptionPane.showMessageDialog(null, "El producto no está");
        }
    }//GEN-LAST:event_TipProductoProductoActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            getToolkit().beep();//Genera el sonido
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            getToolkit().beep();//Genera el sonido
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void GuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarProductoActionPerformed
        if (z.CrearProducto(txtTipProducto.getText().trim(), txtColeccion.getText().trim(), txtCantidad.getText().trim(), txtPrecio.getText().trim())) {
            txtPrecio.setText("");
            txtCantidad.setText("");
            txtColeccion.setText("");
            txtTipProducto.setText("");
            JOptionPane.showMessageDialog(null, "Producto guardado");
        } else {
            txtPrecio.setText("");
            txtCantidad.setText("");
            txtColeccion.setText("");
            txtTipProducto.setText("");
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }
    }//GEN-LAST:event_GuardarProductoActionPerformed

    private void GuardarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarProducto1ActionPerformed

    private void GuardarProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarProducto2ActionPerformed
        ListaProducto nuevo = new ListaProducto(null,true);
        nuevo.setVisible(true);        
    }//GEN-LAST:event_GuardarProducto2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ColeccionProducto;
    private javax.swing.JButton GuardarColeccion;
    private javax.swing.JButton GuardarProducto;
    private javax.swing.JButton GuardarProducto1;
    private javax.swing.JButton GuardarProducto2;
    private javax.swing.JButton GuardarTipProducto;
    private javax.swing.JButton ListarColeccion;
    private javax.swing.JButton ListarTipProducto;
    private javax.swing.JTable TablaColeccion;
    private javax.swing.JTable TablaTipProducto;
    private javax.swing.JButton TipProductoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtColeccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtTipProducto;
    private javax.swing.JTextField txtTrimestre;
    // End of variables declaration//GEN-END:variables
}
