/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.formularios;

/**
 *
 * @author gusta_000
 */
public class formularios extends javax.swing.JFrame {

    /**
     * Creates new form formularios
     */
    public formularios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAlmacen = new javax.swing.JTabbedPane();
        pWelcome = new javax.swing.JPanel();
        jLabTitulo = new javax.swing.JLabel();
        jLabMensaje = new javax.swing.JLabel();
        btonProducto = new javax.swing.JButton();
        btonAlmacen = new javax.swing.JButton();
        btonVenta = new javax.swing.JButton();
        btonReporte = new javax.swing.JButton();
        btoncerrar = new javax.swing.JButton();
        imgPortada = new javax.swing.JLabel();
        pRegProducto = new javax.swing.JPanel();
        tituloVentanaProducto = new javax.swing.JLabel();
        tipoProductoL = new javax.swing.JLabel();
        tipoProductoCB = new javax.swing.JComboBox<>();
        coleccionL = new javax.swing.JLabel();
        txtColeccion = new javax.swing.JTextField();
        pRegAlmacen = new javax.swing.JPanel();
        pVentas = new javax.swing.JPanel();
        pReportes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pAlmacen.setFont(new java.awt.Font("Batang", 1, 12)); // NOI18N

        pWelcome.setLayout(null);

        jLabTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabTitulo.setFont(new java.awt.Font("Goudy Stout", 1, 22)); // NOI18N
        jLabTitulo.setText("CUEROS DE AMÉRICA");
        pWelcome.add(jLabTitulo);
        jLabTitulo.setBounds(299, 92, 439, 31);

        jLabMensaje.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabMensaje.setForeground(new java.awt.Color(255, 255, 255));
        jLabMensaje.setText("¡La moda al alcance de Todos y más aún con material 100% calidad!");
        pWelcome.add(jLabMensaje);
        jLabMensaje.setBounds(52, 447, 559, 21);

        btonProducto.setBackground(new java.awt.Color(255, 255, 255));
        btonProducto.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        btonProducto.setText("Registrar Productos");
        btonProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonProductoActionPerformed(evt);
            }
        });
        pWelcome.add(btonProducto);
        btonProducto.setBounds(394, 179, 155, 25);

        btonAlmacen.setBackground(new java.awt.Color(255, 255, 255));
        btonAlmacen.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        btonAlmacen.setText("Registrar Almacén");
        btonAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonAlmacenActionPerformed(evt);
            }
        });
        pWelcome.add(btonAlmacen);
        btonAlmacen.setBounds(394, 239, 143, 25);

        btonVenta.setBackground(new java.awt.Color(255, 255, 255));
        btonVenta.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        btonVenta.setText("Registrar venta");
        btonVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonVentaActionPerformed(evt);
            }
        });
        pWelcome.add(btonVenta);
        btonVenta.setBounds(394, 291, 125, 25);

        btonReporte.setBackground(new java.awt.Color(255, 255, 255));
        btonReporte.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        btonReporte.setText(" Informe");
        btonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonReporteActionPerformed(evt);
            }
        });
        pWelcome.add(btonReporte);
        btonReporte.setBounds(394, 346, 83, 25);

        btoncerrar.setBackground(new java.awt.Color(255, 102, 102));
        btoncerrar.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        btoncerrar.setText("Cerrar");
        btoncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoncerrarActionPerformed(evt);
            }
        });
        pWelcome.add(btoncerrar);
        btoncerrar.setBounds(394, 397, 73, 25);
        pWelcome.add(imgPortada);
        imgPortada.setBounds(0, 0, 910, 490);

        pAlmacen.addTab("Bienvenida", pWelcome);

        tituloVentanaProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tituloVentanaProducto.setText("DATOS PRODUCTO");

        tipoProductoL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tipoProductoL.setText("TIPO PRODUCTO");

        tipoProductoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Billeteras", "Chaquetas", "Correas", "Morrales", "Sandalias", "Sombreros", "Zapatos" }));

        coleccionL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        coleccionL.setText("COLECCIÓN");

        javax.swing.GroupLayout pRegProductoLayout = new javax.swing.GroupLayout(pRegProducto);
        pRegProducto.setLayout(pRegProductoLayout);
        pRegProductoLayout.setHorizontalGroup(
            pRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegProductoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(pRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloVentanaProducto)
                    .addGroup(pRegProductoLayout.createSequentialGroup()
                        .addGroup(pRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoProductoL)
                            .addComponent(coleccionL))
                        .addGap(68, 68, 68)
                        .addGroup(pRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoProductoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(616, Short.MAX_VALUE))
        );
        pRegProductoLayout.setVerticalGroup(
            pRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRegProductoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tituloVentanaProducto)
                .addGap(33, 33, 33)
                .addGroup(pRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoProductoL)
                    .addComponent(tipoProductoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pRegProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coleccionL)
                    .addComponent(txtColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(345, Short.MAX_VALUE))
        );

        pAlmacen.addTab("Registro Productos", pRegProducto);

        javax.swing.GroupLayout pRegAlmacenLayout = new javax.swing.GroupLayout(pRegAlmacen);
        pRegAlmacen.setLayout(pRegAlmacenLayout);
        pRegAlmacenLayout.setHorizontalGroup(
            pRegAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        pRegAlmacenLayout.setVerticalGroup(
            pRegAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        pAlmacen.addTab("Registro Almacén", pRegAlmacen);

        javax.swing.GroupLayout pVentasLayout = new javax.swing.GroupLayout(pVentas);
        pVentas.setLayout(pVentasLayout);
        pVentasLayout.setHorizontalGroup(
            pVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        pVentasLayout.setVerticalGroup(
            pVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        pAlmacen.addTab("Registro Ventas", pVentas);

        javax.swing.GroupLayout pReportesLayout = new javax.swing.GroupLayout(pReportes);
        pReportes.setLayout(pReportesLayout);
        pReportesLayout.setHorizontalGroup(
            pReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        pReportesLayout.setVerticalGroup(
            pReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        pAlmacen.addTab("Informes", pReportes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pAlmacen, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pAlmacen)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btonProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonProductoActionPerformed
         pAlmacen.setSelectedIndex(1);
    }//GEN-LAST:event_btonProductoActionPerformed

    private void btonAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonAlmacenActionPerformed
        pAlmacen.setSelectedIndex(2);
    }//GEN-LAST:event_btonAlmacenActionPerformed

    private void btonVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonVentaActionPerformed
        pAlmacen.setSelectedIndex(3);
    }//GEN-LAST:event_btonVentaActionPerformed

    private void btonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonReporteActionPerformed
        pAlmacen.setSelectedIndex(4);
    }//GEN-LAST:event_btonReporteActionPerformed

    private void btoncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoncerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btoncerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btonAlmacen;
    private javax.swing.JButton btonProducto;
    private javax.swing.JButton btonReporte;
    private javax.swing.JButton btonVenta;
    private javax.swing.JButton btoncerrar;
    private javax.swing.JLabel coleccionL;
    private javax.swing.JLabel imgPortada;
    private javax.swing.JLabel jLabMensaje;
    private javax.swing.JLabel jLabTitulo;
    private javax.swing.JTabbedPane pAlmacen;
    private javax.swing.JPanel pRegAlmacen;
    private javax.swing.JPanel pRegProducto;
    private javax.swing.JPanel pReportes;
    private javax.swing.JPanel pVentas;
    private javax.swing.JPanel pWelcome;
    private javax.swing.JComboBox<String> tipoProductoCB;
    private javax.swing.JLabel tipoProductoL;
    private javax.swing.JLabel tituloVentanaProducto;
    private javax.swing.JTextField txtColeccion;
    // End of variables declaration//GEN-END:variables
}
